### ISSUE TITLE
tests fails

### ISSUE THREAD

**Issue by sphrak** [sphrak/django-docker#1]
something is whack with the test image
```bash
======================================================================
FAIL: test_readonly_root (file_uploads.tests.DirectoryCreationTests)
Permission errors are not swallowed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.5/unittest/case.py", line 600, in run
    testMethod()
  File "/django/tests/file_uploads/tests.py", line 547, in test_readonly_root
    self.obj.testfile.save('foo.txt', SimpleUploadedFile('foo.txt', b'x'), save=False)
  File "/usr/lib/python3.5/unittest/case.py", line 198, in __exit__
    self._raiseFailure("{} not raised".format(exc_name))
  File "/usr/lib/python3.5/unittest/case.py", line 134, in _raiseFailure
    raise self.test_case.failureException(msg)
AssertionError: PermissionError not raised

======================================================================
FAIL: test_permissions_error (template_tests.test_loaders.FileSystemLoaderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.5/unittest/case.py", line 600, in run
    testMethod()
  File "/django/tests/template_tests/test_loaders.py", line 202, in test_permissions_error
    self.engine.get_template(tmpfile.name)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/django/django/test/testcases.py", line 591, in _assert_raises_message_cm
    yield cm
  File "/usr/lib/python3.5/unittest/case.py", line 198, in __exit__
    self._raiseFailure("{} not raised".format(exc_name))
  File "/usr/lib/python3.5/unittest/case.py", line 134, in _raiseFailure
    raise self.test_case.failureException(msg)
AssertionError: OSError not raised

----------------------------------------------------------------------
Ran 12467 tests in 337.291s

FAILED (failures=2, skipped=313, expected failures=8)
```

**Comment by sphrak** [comment]
solved
